export const PIE_IMAGES: { [index: number]: string } = {
  0: "assets/pie01.png",
  1: "assets/pie02.png",
  2: "assets/pie03.png",
  3: "assets/pie04.png",
  4: "assets/pie05.png",
  5: "assets/pie06.png",
  6: "assets/pie07.png",
  7: "assets/pie08.png",
  8: "assets/pie09.png",
  9: "assets/pie10.png",
};

export const PIZZA_IMAGES: { [key: string]: { [index: number]: string }} = {
  attr1: {
    0: "assets/dog01.png",
    1: "assets/dog02.png",
    2: "assets/dog06.png",
    3: "assets/dog04.png",
    4: "assets/dog05.png",
    5: "assets/dog07.png",
    6: "assets/dog03.png",
  },
  attr2: {
    0: "assets/dog01.png",
    1: "assets/dog02.png",
    2: "assets/dog06.png",
    3: "assets/dog04.png",
    4: "assets/dog05.png",
    5: "assets/dog07.png",
    6: "assets/dog03.png",
  },
  attr3: {
    0: "assets/dog01.png",
    1: "assets/dog02.png",
    2: "assets/dog06.png",
    3: "assets/dog04.png",
    4: "assets/dog05.png",
    5: "assets/dog07.png",
    6: "assets/dog03.png",
  },
  attr4: {
    0: "assets/dog01.png",
    1: "assets/dog02.png",
    2: "assets/dog06.png",
    3: "assets/dog04.png",
    4: "assets/dog05.png",
    5: "assets/dog07.png",
    6: "assets/dog03.png",
  },
};
